name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install pandoc
      run: sudo apt-get install pandoc

    - name: Create H1
      working-directory: h1
      run: make

    - name: List files in H1
      working-directory: h1
      run: ls -lah
